name: Deploy Shiny App

on:
  push:
    branches:
      - main  # Change this to your primary branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          Rscript -e "install.packages('rsconnect')"

      - name: Deploy Shiny App
        env:
          SHINYAPPSIO_ACCOUNT: carsonjs
          SHINYAPPSIO_TOKEN: B9172B818D83F52A8EF4FC6F5D7685BC
          SHINYAPPSIO_SECRET: ve6i2mgQ9JXugUhRr71nwQWVOclmv/DUsJTo0Ku2
        run: |
          Rscript -e "rsconnect::setAccountInfo(name=Sys.getenv('SHINYAPPSIO_ACCOUNT'), token=Sys.getenv('SHINYAPPSIO_TOKEN'), secret=Sys.getenv('SHINYAPPSIO_SECRET'))"
          Rscript -e "rsconnect::deployApp()"
